### ISSUE TITLE
Astro error "window is not defined" in @vueform/vueform/dist/tailwind.mjs

### ISSUE THREAD

**Issue by preetamslot** [vueform/vueform#152]
### Environment

Astro 4.4, Tailwind 3.4.1, Vue 3.4.20, npm 10.2.4, node 20.11.0, @vueform/vueform 1.8.0
Astro in static and server mode (netlify)

### Reproduction

Follow the installation steps for astro
run dev

### Describe the bug

On dev I get the error:
```
Astro detected an unhandled rejection. Here's the stack trace:
ReferenceError: window is not defined
    at file:///C:/SITES/XXXXXX/node_modules/@vueform/vueform/dist/tailwind.mjs:12806:51
    at file:///C:/SITES/XXXXXX/node_modules/@vueform/vueform/dist/tailwind.mjs:12806:524
    at file:///C:/SITES/XXXXXX/node_modules/@vueform/vueform/dist/tailwind.mjs:12822:3
```

### Logs

```shell-script
16:17:28 [ERROR] [UnhandledRejection] Astro detected an unhandled rejection. Here's the stack trace:
ReferenceError: window is not defined
    at file:///C:/SITES/xxxx/node_modules/@vueform/vueform/dist/tailwind.mjs:12806:51
    at file:///C:/SITES/xxxx/node_modules/@vueform/vueform/dist/tailwind.mjs:12806:524
    at file:///C:/SITES/xxxx/node_modules/@vueform/vueform/dist/tailwind.mjs:12822:3
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async nodeImport (file:///C:/SITES/xxxx/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:54763:17)   
    at async ssrImport (file:///C:/SITES/xxxx/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:54663:24)    
    at async eval (C:/SITES/xxxx/vueform.config.ts:5:31)
    at async instantiateModule (file:///C:/SITES/axxxx/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:54725:9)
```

**Comment by preetamslot** [comment]
The only way it works in dev for me is to edit the _app.ts

```
if(typeof window !== 'undefined') {
      const vueformConfig = (await import('../../vueform.config')).default
       app.use(Vueform, vueformConfig);  
     }

```

**Comment by adamberecz** [comment]
I'm not able to reproduce this with `static` or `server` (+ netlify adapter) output, neither in `dev` or `build`.

Are you sure your initial setup looked like this?
```js
// src/pages/_app.ts

import type { App } from 'vue';
import Vueform from '@vueform/vueform'

export default async (app: App) => {
  const vueformConfig = (await import('../../vueform.config')).default
  app.use(Vueform, vueformConfig)
}
```

**Comment by eslamodeh** [comment]
This is happening to me as well. I am using Netlify with hybrid adapter. Any updates regarding this please?
